config/routes.rb
Selfstarter::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  # This must come before general routes to ensure proper redirects
  constraints(TripSubdomain) do
    match "/" => redirect("/go")
    match "go" => "trips#show", :as => :trip
    get "checkout" => "orders#new"
    match 'checkout' => "orders#create", :via => :post
    match "orders/:id" => "orders#show", :as => :order
  end

  root :to => "home#index"
  match "/go" => redirect("/"), :constraints => {:subdomain => 'www'}
  match "/checkout" => redirect("/"), :constraints => {:subdomain => 'www'}
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :city, :end_date, :name, :price, :start_date, :expiration_date, :state, :code, :goal

  has_many :trip_items
  has_many :orders
  has_many :attendees, :through => :orders, :source => :user

  validates :name, :presence => true
  validates :price, :numericality => {:precision => 8, :scale => 2, :allow_nil => true}
  validates :code, :uniqueness => true
  validates :goal, :numericality => {:greater_than_or_equal_to => 0}
  validates :start_date, :date => {:before_or_equal_to => :end_date}, :allow_nil => true
  validates :end_date, :date => {}, :allow_nil => true
  validates :expiration_date, :date => {:before_or_equal_to => :end_date}, :allow_nil => true

  def human_price
    "Only $" + price.to_s
  end

  def price_in_cents
    (price * 100).to_i
  end

  def faq_items
    trip_items.with_type(:faq)
  end
  def key_point_items
    trip_items.with_type(:key_point)
  end
  def other_point_items
    trip_items.with_type(:other_point)
  end
  def attending
    attendees.count
  end
  def remaining
    remain = goal - attending
    remain < 0 ? 0 : remain
  end
  def goal_percent
    (attending.to_f / goal.to_f) * 100.to_f
  end
  def revenue
    attending.to_f * price
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # skip_before_filter :verify_authenticity_token, :only => :ipn

  before_filter :set_page_title
  before_filter :set_trip

  def show
  end

  def checkout!
    @user = User.find_or_create_by_email!(params[:email])
    redirect_to root_url unless params[:stripe_token]

    # Create a Stripe customer that we can charge later, and
    # attach the customer ID to the User object.
    customer = Stripe::Customer.create(
      :description => "Customer for #{params[:email]}",
      :email => params[:email],
      :card => params[:stripe_token]
    )

    # Create an order for this user.
    @order = Order.generate
    @order.stripe_customer_id = customer.id
    @order.name = Settings.product_name
    @order.price = Settings.trip.price
    @order.user_id = @user.id
    @order.address_line1 = params[:address_line1]
    @order.address_line2 = params[:address_line2]
    @order.city = params[:city]
    @order.state = params[:state]
    @order.phone = params[:phone]
    @order.zip = params[:address_zip]
    @order.country = params[:country]
    @order.save!

    redirect_to root_url
  end

  def share
    @order = Order.find_by_uuid(params[:uuid])
  end

  private
  # TODO: Refactor to use i18n
  def set_page_title
    @page_title = current_trip.name
  end
  def set_trip
    @trip = current_trip
  end
end

app/helpers/trips_helper.rb
module TripsHelper
  def trip_dates
    start_date = @trip.start_date
    end_date = @trip.end_date
    if start_date.year != end_date.year
      start_date.strftime('%B %-d, %Y - ') + end_date.strftime('%B %-d, %Y')
    elsif start_date.month != end_date.month
      start_date.strftime('%B %-d - ') + end_date.strftime('%B %-d, %Y')
    else
      start_date.strftime('%B %-d-') + end_date.strftime('%-d, %Y')
    end
  end
end

app/views/trips/homepage/_faq.html.erb
<li class=''>
  <details class=''>
    <summary class=''><%= raw faq.title %></summary>
    <p>
      <%= raw faq.body %>
    </p>
  </details>
</li>

app/views/trips/homepage/_faqs.html.erb
<% unless @trip.faq_items.empty? %>
<div class="gray_background" id="faqs">
    <div class="wrapper clearfix">
      <h4>Frequently Asked Questions</h4>
        <ul>
          <% @trip.faq_items.slice(0, (@trip.faq_items.size/2.0).ceil).each do |faq| %>
              <%= render 'trips/homepage/faq', faq: faq %>
            <%	end  %>
        </ul>
        <ul class='col2'>
          <% @trip.faq_items.slice((@trip.faq_items.size/2.0).ceil..-1).each do |faq| %>
              <%= render 'trips/homepage/faq', faq: faq %>
          <%	end  %>
        </ul>
    </div>
</div>
<% end %>

app/views/trips/homepage/_key_points.html.erb
<% @trip.key_point_items.each do |key_point| %>
  <div class="big_wrapper">
    <div class="wrapper" id="<%= 'key_point_' + key_point.position.to_s %>">
      <div class="point_copy <%= cycle('', 'right') %>">
        <h3>
          <%= raw key_point.title %>
        </h3>
        <p>
          <%= raw key_point.body %>
        <p>
      </div>
    </div>
  </div>
<% end %>

app/views/trips/homepage/_middle_reserve.html.erb
<div class="big_wrapper">
  <div class="wrapper center" id="middle_reserve">
    <h2><%= Settings.call_to_action_two %></h2>
    <%= link_to Settings.middle_reserve_text, checkout_path, :class => "blue_button reserve" %>
  </div>
</div>

app/views/trips/homepage/_other_points.html.erb
<div class="gray_background">
  <ul class="wrapper clearfix" id="other_points">
    <% @trip.other_point_items.each do |other_point| %>
      <li id="section-<%= other_point.position %>">
        <h4><%= raw other_point.title %></h4>
        <p><%= raw other_point.body %></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/trips/homepage/_press.html.erb
<div id='logos'>
	<ul class="wrapper clearfix">
	  <li id="awesomeblog"><a href=""></a></li>
	  <li id="coolpaper"><a href=""></a></li>
	  <li id="nicemag"><a href=""></a></li>
	  <li id="readcrunch"><a href=""></a></li>
	</ul>
</div>

app/views/trips/homepage/_show_dont_tell.html.erb
<div class="gray_background">
  <%= render 'trips/homepage/stats' %>
</div>

app/views/trips/homepage/_stats.html.erb
<div class="wrapper clearfix">
  <div id="visual">
    <iframe width='512' height='385' src="<%= Settings.youtube_embed_url %>?autohide=1&showinfo=0&rel=0&autoplay=0"></iframe>
  </div>

  <div id="backing">

    <ul>
      <li class="stats" id="backers">
        <%= number_with_delimiter @trip.attending, :delimiter => "," %>
        <span><%= Settings.primary_stat %></span>
      </li>

      <% unless @trip.expiration_date.blank? %>
        <li class="stats" id="days">
          <%= distance_of_time_in_words_to_now(@trip.expiration_date).gsub(/\D/, "") %>
          <span><%= distance_of_time_in_words_to_now(@trip.expiration_date).gsub(/\d/, "").gsub("about", "") %> left</span>
        </li>
      <% else %>
        <li class="stats" id="days">
            &infin;
            <span>days left</span>
          </li>
      <% end %>
    </ul>

    <% if @trip.attending < @trip.goal %>
      <div id='progress_bg' class='small'>
        <div id='progress' class='' style='width: <%= @trip.goal_percent %>%;'>
        </div>
        <div id='progress_text' class="incomplete"><%= @trip.remaining %> more makes it happen!</div>
      </div>
    <% else %>
      <div id="progress_bg">
        <div id="progress">
        </div>
        <div id='progress_text'><%= @trip.goal_percent %>% <%= Settings.progress_text %></div>
      </div>
    <% end %>
    
    <div id="reserve_container">
      <p id="ship_date">
        <%= trip_dates %>
        <br>in <%= @trip.city %>
      </p>
      <%= link_to Settings.call_to_action, checkout_path, :class => "blue_button reserve" %>
      <p id="price"><%= "Only " + number_to_currency(@trip.price) %></p>
      <p><%= Settings.dont_give_them_a_reason_to_say_no %></p>
      <%= like_button %>
    </div>

  </div>
  
</div>

app/views/trips/homepage/_value_proposition.html.erb
<div class="wrapper center">
  <h2><%= Settings.value_proposition %></h2>
</div>